---
name: ${NAME}

services:
  curl:
    image: curlimages/curl
    depends_on:
      lambda:
        condition: service_healthy
    command: 
      - -s
      - -d
      - "@/work/event.json"
      - lambda:8080/2015-03-31/functions/function/invocations
    volumes:
      - ./events:/work:ro
  lambda:
    build:
      target: lambda
  dev:
    build:
      target: dev
    profiles:
      - dev
    volumes:
      - ./app:/app
